# Generated by Django 5.2.16 on 2026-07-12 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('license', models.CharField(max_length=40, unique=True)),
                ('safety_score', models.IntegerField(default=95)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Service', 'In Service'), ('Maintenance', 'Maintenance'), ('Idle', 'Idle'), ('Retired', 'Retired'), ('On Duty', 'On Duty'), ('Off Duty', 'Off Duty'), ('Sick', 'Sick'), ('Suspended', 'Suspended'), ('Pending', 'Pending'), ('Loading', 'Loading'), ('On Route', 'On Route'), ('Delayed', 'Delayed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Active', max_length=24)),
                ('hours', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=40)),
                ('avatar_color', models.CharField(default='bg-indigo-600', max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('license_category', models.CharField(blank=True, default='', max_length=60)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, default='', max_length=60)),
                ('total_distance', models.IntegerField(default=0)),
                ('fuel_efficiency', models.CharField(blank=True, default='', max_length=40)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('recent_activity', models.JSONField(blank=True, default=list)),
                ('performance_timeline', models.JSONField(blank=True, default=list)),
                ('upcoming_trips_count', models.IntegerField(default=0)),
                ('today_distance', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Fuel', 'Fuel'), ('Maintenance', 'Maintenance'), ('Driver Salary', 'Driver Salary'), ('Insurance', 'Insurance'), ('Tolls & Permits', 'Tolls & Permits'), ('Other', 'Other')], max_length=40)),
                ('amount', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_id', models.CharField(max_length=32)),
                ('volume', models.FloatField(default=0)),
                ('price_per_unit', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('odometer', models.IntegerField(default=0)),
                ('station', models.CharField(max_length=120)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_id', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=120)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Critical', 'Critical')], default='Medium', max_length=24)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Service', 'In Service'), ('Maintenance', 'Maintenance'), ('Idle', 'Idle'), ('Retired', 'Retired'), ('On Duty', 'On Duty'), ('Off Duty', 'Off Duty'), ('Sick', 'Sick'), ('Suspended', 'Suspended'), ('Pending', 'Pending'), ('Loading', 'Loading'), ('On Route', 'On Route'), ('Delayed', 'Delayed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=24)),
                ('cost', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('technician', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=40)),
                ('unread', models.BooleanField(default=True)),
                ('type', models.CharField(default='info', max_length=24)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.CharField(default='default', editable=False, max_length=16, primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=160)),
                ('address', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=64)),
                ('currency', models.CharField(max_length=40)),
                ('timezone', models.CharField(max_length=80)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('density', models.CharField(choices=[('High', 'High'), ('Compact', 'Compact'), ('Standard', 'Standard')], default='High', max_length=20)),
                ('theme', models.CharField(choices=[('Light', 'Light'), ('Slate', 'Slate'), ('Dark', 'Dark')], default='Light', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_id', models.CharField(max_length=32)),
                ('driver_id', models.CharField(max_length=32)),
                ('destination', models.CharField(max_length=120)),
                ('departure', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Service', 'In Service'), ('Maintenance', 'Maintenance'), ('Idle', 'Idle'), ('Retired', 'Retired'), ('On Duty', 'On Duty'), ('Off Duty', 'Off Duty'), ('Sick', 'Sick'), ('Suspended', 'Suspended'), ('Pending', 'Pending'), ('Loading', 'Loading'), ('On Route', 'On Route'), ('Delayed', 'Delayed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=24)),
                ('eta', models.CharField(max_length=60)),
                ('progress', models.IntegerField(default=0)),
                ('freight', models.CharField(max_length=160)),
                ('cost', models.FloatField(default=0)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('plate', models.CharField(max_length=40, unique=True)),
                ('type', models.CharField(choices=[('Heavy Truck', 'Heavy Truck'), ('Delivery Van', 'Delivery Van'), ('Electric Carrier', 'Electric Carrier')], max_length=40)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Service', 'In Service'), ('Maintenance', 'Maintenance'), ('Idle', 'Idle'), ('Retired', 'Retired'), ('On Duty', 'On Duty'), ('Off Duty', 'Off Duty'), ('Sick', 'Sick'), ('Suspended', 'Suspended'), ('Pending', 'Pending'), ('Loading', 'Loading'), ('On Route', 'On Route'), ('Delayed', 'Delayed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Active', max_length=24)),
                ('fuel', models.FloatField(default=100)),
                ('health', models.FloatField(default=100)),
                ('capacity', models.CharField(max_length=40)),
                ('last_service', models.DateField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Driver', 'Driver')], default='Admin', max_length=20)),
                ('driver_id', models.CharField(blank=True, default='', max_length=32)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
